### ISSUE TITLE
localerefresh and l10n repo pushing

### ISSUE THREAD

**Issue by peterbe** [mdn/kuma-deployer#1]
At the time of writing, there's a [`localerefresh.py`](https://github.com/mdn/kuma-deployer/blob/54f1910ff354e2d28ff6230090f910e08a493430/deployer/localerefresh.py) which is meant to do all the l10n chores. 

It's goal is simple: Automate all of steps 1-6 on https://kuma.readthedocs.io/en/latest/deploy.html

At the moment, all the script does trigger a `docker-compose exec web make localerefresh` but it doesn't know how to figure out if there were relevant messages worth pushing. 

First challenge: How do you write that regex on the diff??

**Comment by peterbe** [comment]
I ran `localerefresh` and then...

```
cd locale
git diff
```

Grossly, the `git diff` is huuuuge. 
```
▶ git diff | wc -l
   74383
```
Also,
```
129 files changed, 15173 insertions(+), 15287 deletions(-)
```

Skimming through the best I see things like this:
<img width="630" alt="Screen Shot 2019-08-29 at 2 13 46 PM" src="https://user-images.githubusercontent.com/26739/63965665-a6c6cf00-ca67-11e9-9a01-60bf6409d5ef.png">

Basically, I need to figure out the argument to reset vs. commit.

**Comment by peterbe** [comment]
If I run `git diff | rg msgid` I get this output:
<img width="1100" alt="Screen Shot 2019-08-29 at 2 19 59 PM" src="https://user-images.githubusercontent.com/26739/63965879-26549e00-ca68-11e9-942d-4238cb94901a.png">

**Comment by peterbe** [comment]
What do you think @escattone ?
<img width="935" alt="Screen Shot 2019-08-29 at 2 59 19 PM" src="https://user-images.githubusercontent.com/26739/63968414-a29db000-ca6d-11e9-9a43-0511f0fe659c.png">

Does this look right? If so, I can proceed with the other [steps related to l10n](https://kuma.readthedocs.io/en/latest/deploy.html).

**Comment by escattone** [comment]
@peterbe Yes! That looks spot on! Within `vi` I always use `/\+msgid` as my search for new strings.
